
project_id = "uqoxukprtmpnpsnxngog"

[functions.send-email]
verify_jwt = false

[functions.extract-cv-content]
verify_jwt = false

[functions.redesign-cv]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = false
