// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdocxltqafuflamgtydn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpkb2N4bHRxYWZ1ZmxhbWd0eWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODgzMzUsImV4cCI6MjA2MTE2NDMzNX0.jQAzTht2LAgsFTXPJIJ2q96j4nYGTE2UdV3M2iXTMIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);