// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqoxukprtmpnpsnxngog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxb3h1a3BydG1wbnBzbnhuZ29nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NjMwMjIsImV4cCI6MjA2MTIzOTAyMn0.gdeaBAKouFx4Le95v7yRds-g6wTWl9Vk09sB3ZjMzRU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);